// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:855a1f0d-479e-4cb6-bfe9-bc648ca09f83",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_dgo4eFYnc",
    "aws_user_pools_web_client_id": "18j08hsapglcrrniv5fn1madb4"
};


export default awsmobile;
